upgrade CoroutineWarning to DeprecationWarning
pytest-dev/pytest pull request #10012
Opened 2022-06-01 16:31 UTC by graingert

2022-07-29 09:37 UTC, graingert commented on src/_pytest/warning_types.py
>  class PytestReturnNotNoneWarning(PytestDeprecationWarning):
@RonnyPfannschmidt requested that PytestReturnNotNoneWarning be a RemovedIn8Warning and I agree

2022-07-31 13:00 UTC, nicoddemus requested changes
Looks good, however I think this warrants a changelog entry?

2022-08-03 23:03 UTC, nicoddemus commented on changelog/10012.deprecation.rst
> +upgrade :class:`pytest.PytestUnhandledCoroutineWarning` to a deprecation it will raise an error in pytest 8
```suggestion
Change :class:`pytest.PytestUnhandledCoroutineWarning` to a deprecation; it will raise an error in pytest 8.
```

2022-08-05 10:12 UTC, graingert commented
@nicoddemus what do you think about making RemovedIn8Warning not-final?

2022-08-05 11:46 UTC, nicoddemus commented
I'm OK with making it not-final 👍

2022-08-05 11:47 UTC, nicoddemus approved these changes

2022-08-06 11:45 UTC, RonnyPfannschmidt approved these changes

2022-08-08 09:14 UTC, merged