Fix checking expected warnings when an exception is raised
pytest-dev/pytest pull request #10208
Opened 2022-08-12 10:18 UTC by eltimen

Fixes #9036 
The behavior in the issue is observed because `pytest.warn` don't capture warnings when an exception is raised inside a `with` block due to the condition in `WarningsChecker.__exit__`. 
It looks like removing this condition should fix this bug, Or is it needed to cover some case?

2022-08-12 10:20 UTC, RonnyPfannschmidt requested changes
This is a breaking change to intended behaviour,

Else the other exception gets hidden

2022-08-12 10:33 UTC, eltimen commented
Hello @RonnyPfannschmidt. Could you please clarify what you mean by "other exception gets hidden" (with a minimal example, if possible)?

2022-08-12 10:47 UTC, RonnyPfannschmidt commented
If the code that should warn
Raises any exception, the new exception supersedes it

2022-08-19 12:21 UTC, closed without merging

2023-06-19 00:59 UTC, Zac-HD commented
@RonnyPfannschmidt I think we _should_ replace the existing error with a `Failed` (because no matching warning); otherwise this nasty issue is just unsolvable.  Fortunately exception chaining will ensure that users can see the superseded exception too.

Can't re-open this when the upstream repo has been deleted, but I'll open a new one soon.