Stop using `atexit` and add integration tests for `tmpdir` fixture
pytest-dev/pytest pull request #10546
Opened 2022-11-29 14:37 UTC by yusuke-kadowaki

Closes https://github.com/pytest-dev/pytest/issues/10545

2022-11-29 14:54 UTC, RonnyPfannschmidt requested changes
it ts a good idea to make this boundary more clear :+1: 

lets try to go with existing tools from the stdlib and make sure we trigger all we need on errors as well

2022-11-30 14:14 UTC, yusuke-kadowaki commented on testing/test_tmpdir.py
> +            base_dir = filter(lambda x: x.is_dir(), child.iterdir())
Thanks for pointing out.
12cba4a

2022-11-30 14:15 UTC, yusuke-kadowaki commented on src/_pytest/pathlib.py
> +    register=atexit.register,
Didn't know about the stdlib. I find it really cool.
[58c5d50](https://github.com/pytest-dev/pytest/pull/10546/commits/58c5d5089a35ae00a852ec9bbf655c7d3a863195)

2022-11-30 14:17 UTC, yusuke-kadowaki commented on src/_pytest/tmpdir.py
> +    tmp_path_factory._lock_and_dir_removal_callback.execute()
> i recall the atexit registration was done to ensure cleanup even when sessionfinish fails (rare, but can happen)

I wasn't aware of that situation. Now it's good I think.
[58c5d50](https://github.com/pytest-dev/pytest/pull/10546/commits/58c5d5089a35ae00a852ec9bbf655c7d3a863195)

2022-12-01 17:09 UTC, RonnyPfannschmidt approved these changes
with the exitstack this looks good to me now :+1: 

lets register a followup to turn `make_numbered_dir_with_cleanup` into a actual context manager that one can push into the exitstack

but before we do more exit stacks, i think we want to take a look for pytest-core about where and how to use exit stacks / context managers in future/for code cleanup

2022-12-03 07:39 UTC, yusuke-kadowaki reviewed
Refactored some test code.
[5e6ce8f](https://github.com/pytest-dev/pytest/pull/10546/commits/5e6ce8f43306be77d54cf131f53f5012f2d8a785)

2022-12-03 07:39 UTC, yusuke-kadowaki commented on testing/test_tmpdir.py
> -            assert len(list(base_dir)) == 0
Removed this because it's now a duplicate of `test_retention_count`

2022-12-03 07:53 UTC, yusuke-kadowaki commented
> lets register a followup to turn `make_numbered_dir_with_cleanup` into a actual context manager that one can push into the exitstack

I'm not really understanding the motivation of using context manager for it.
Does it change anything in this case to use `ExitStack.enter_context` over `ExitStack.callback`?

2026-05-03 06:42 UTC, bluetech commented
I like the idea of removing reliance on atexit. I rebased the PR on current main.

However, @RonnyPfannschmidt's first review mentioned that atexit was used as a fallback to remove the locks when even `sessionfinish` fails, an IIUC Ronny meant to use both the explicit ExitStack context manager, and atexit. But currently the PR only does the `with _exit_stack`.

@RonnyPfannschmidt did you mean the code should also register an exit stack `close` with `atexit` as a safety, or are you fine without it?

2026-05-03 07:27 UTC, RonnyPfannschmidt commented
I recall that sometimes its necessary 

But registring the close for atexit is way cleaner than what we had

2026-05-03 19:02 UTC, bluetech commented
Alright, added back a last-resort atexit, and made a few other tweaks to the PR. Can merge this now.

2026-05-03 19:03 UTC, bluetech approved these changes

2026-05-03 19:14 UTC, merged