Fix option error
pytest-dev/pytest pull request #10608
Opened 2022-12-24 03:38 UTC by markshao

close #10592 

Thanks for submitting a PR, your contribution is really appreciated!

Here is a quick checklist that should be present in PRs.

- [X] Include documentation when adding new features.
- [X] Include new tests or update existing tests when applicable.
- [X] Allow maintainers to push and squash when merging my commits. Please uncheck this if you prefer to squash the commits yourself.

If this change fixes an issue, please:

- [X] Add text like ``closes #XYZW`` to the PR description and/or commits (where ``XYZW`` is the issue number). See the [github docs](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information.

Unless your change is trivial or a small documentation fix (e.g., a typo or reword of a small section) please:

- [X] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/main/changelog/README.rst) for details.

  Write sentences in the **past or present tense**, examples:

  * *Improved verbose diff output with sequences.*
  * *Terminal summary statistics now use multiple colors.*

  Also make sure to end the sentence with a `.`.

- [X] Add yourself to `AUTHORS` in alphabetical order.

2023-01-04 12:24 UTC, nicoddemus requested changes
Hi @markshao,

Thanks  for the PR!

Can you include a simple integration test to ensure this does not regress in the future? Thanks!

2023-01-04 12:26 UTC, nicoddemus commented on changelog/10592.bugfix.rst
> +Fix the bug "--cache-show --help" triggers an internal error
```suggestion
Fixed crash if `--cache-show` and `--help` are passed at the same time.
```

2023-01-13 13:59 UTC, markshao commented
> Hi @markshao,
> 
> Thanks for the PR!
> 
> Can you include a simple integration test to ensure this does not regress in the future? Thanks!

Added , pls take a look

2023-01-19 12:44 UTC, nicoddemus approved these changes
Thanks!

2023-01-19 12:44 UTC, merged