Propagate timestamps from CallInfo to TestReport objects
pytest-dev/pytest pull request #10711
Opened 2023-02-06 11:52 UTC by HTRafal

TestReport objects stored only the information about stage duration. This is not enough to correlate pytest stages with external events. Timestamps are already there in CallInfo. They just needed to be propagated to TestReport objects, so that they can be read when TestReports are exported externally (for example with --reportlog option)

Closes #10710

2023-02-06 20:28 UTC, nicoddemus requested changes
As @RonnyPfannschmidt mentions, we need a unittest for the feature, ideally we also need to ensure that the serialization/unserialization will work for those new attributes if we want to make sure it will also work out of the box with `pytest-reportlog`.

2023-02-06 20:28 UTC, nicoddemus commented on changelog/10710.improvement.rst
> +Added ``start`` and ``stop`` timestamps to ``TestReport`` objects exported to --reportlog.
```suggestion
Added ``start`` and ``stop`` timestamps to ``TestReport`` objects.
```

The `--reportlog` is specific for pytest-reportlog.

2023-02-09 15:09 UTC, RonnyPfannschmidt approved these changes
Looks good, wondering if we have a way to make a unittest for this

2023-02-10 07:22 UTC, HTRafal commented
@RonnyPfannschmidt what do you mean? I added a unit test in testing/test_reports.py that tests serialization of the new fields. That should be enough for pytest-reportlog to work as it only calls pytest_report_to_serializable and saves the result to a json file.

2023-02-10 07:34 UTC, RonnyPfannschmidt commented
The test is indeed enough, it however involves quite some machinery that we currently have no nicely testable way to leave out

2023-02-10 07:37 UTC, RonnyPfannschmidt commented
Aka there should be one test that just verifies the transfer from callinfo to report and a second test that only verifies the serialization

But we lack the infrastructure for those pinpointed tests, so we can't exactly ask for their addition in good conscience

2023-02-10 20:50 UTC, nicoddemus approved these changes
Thanks, looks great!

2023-02-10 20:52 UTC, merged