FormattedExcinfo.get_source: Avoid a crash when source.lines == 0
pytest-dev/pytest pull request #10840
Opened 2023-03-26 15:23 UTC by Kodiologist

This is a small change to some checks in `FormattedExcinfo` to avoid the following internal crash in pytest given pathological traceback information:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "…/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "…/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "…/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "…/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "…/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "…/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "…/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "…/site-packages/_pytest/main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "…/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "…/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "…/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "…/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "…/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "…/site-packages/_pytest/runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "…/site-packages/_pytest/runner.py", line 131, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "…/site-packages/_pytest/runner.py", line 222, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "…/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "…/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "…/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "…/site-packages/_pytest/skipping.py", line 265, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "…/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "…/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "…/site-packages/_pytest/runner.py", line 366, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "…/site-packages/_pytest/reports.py", line 349, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "…/site-packages/_pytest/python.py", line 1823, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>   File "…/site-packages/_pytest/nodes.py", line 484, in _repr_failure_py
INTERNALERROR>     return excinfo.getrepr(
INTERNALERROR>   File "…/site-packages/_pytest/_code/code.py", line 669, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "…/site-packages/_pytest/_code/code.py", line 946, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR>   File "…/site-packages/_pytest/_code/code.py", line 873, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "…/site-packages/_pytest/_code/code.py", line 824, in repr_traceback_entry
INTERNALERROR>     s = self.get_source(source, line_index, excinfo, short=short)
INTERNALERROR>   File "…/site-packages/_pytest/_code/code.py", line 757, in get_source
INTERNALERROR>     lines.append(self.flow_marker + "   " + source.lines[line_index])
INTERNALERROR> IndexError: list index out of range
```

I hit this when running some tests with [Hy](https://github.com/hylang/hy), which sometimes creates AST objects with the wrong position information (due to Hy bugs and to cases of generated code with no real position). This could be construed as a bugfix for pytest, but I don't think the "bug" in question could be triggered with real Python code.

2023-04-04 12:49 UTC, nicoddemus requested changes
Thanks for the contribution!

I think the change is reasonable, and I understand the lack of tests for this specific case.

However for future traceability, could you please:

1. Improve the commit message adding more information about the need for it (similar to what you put in the PR description)
2. Add one or more comments around the change, explaining that use case.
3. Add a CHANGELOG entry; while this should not be user-facing, it is nice to have a changelog entry mentioning that in case this somehow breaks an exotic corner case somewhere.

2023-04-04 13:19 UTC, Kodiologist commented
Done.

2023-04-04 14:52 UTC, nicoddemus commented on changelog/10840.improvement.rst
> +pytest should no longer crash on AST with pathological position attributes.
```suggestion
pytest should no longer crash on AST with pathological position attributes, for example testing AST produced by `Hylang <https://github.com/hylang/hy>__`.
```

2023-04-04 14:53 UTC, nicoddemus approved these changes
Thanks!

2023-04-04 14:59 UTC, nicoddemus commented
Leaving this open for a few days in case somebody wants to take a look at it, after that I will squash-merge. :+1:

2023-04-04 15:02 UTC, Kodiologist commented
Cool. Thanks, Skipper.

2023-04-04 15:22 UTC, RonnyPfannschmidt requested changes
we need a test for the case, else the next re-factoring may break it again

2023-04-04 17:07 UTC, RonnyPfannschmidt commented
As far as I can get, what we need something that creates a bugged ast / code object

2023-04-04 17:46 UTC, Kodiologist commented
I don't think I know pytest's internals well enough to reproduce the crash in a simple way. For example, I tried

```python
import ast

def test_ex():
    p = ast.parse('assert False')
    for thing in (p.body[0], p.body[0].test):
        thing.lineno = 5
        thing.end_lineno = 5
        thing.col_offset = 20
        thing.end_col_offset = 20
    eval(compile(p, 'something.py', 'exec'))
```

and it doesn't crash on pytest 7.2.2.

For what it's worth, here's how you can see the crash with Hy 0.26.0 and pytest 7.2.2:

```sh
$ echo '; hello world' >ex.hy
$ echo '(defn test-e [] (do-mac (quote (raise (ValueError)))))' >>ex.hy
$ echo 'import hy; from ex import test_e' >test.py
$ pytest test.py
```

2023-04-05 00:16 UTC, jakevdp commented
I opened a similar PR in #10868 before seeing this one; it has some unit tests that would be applicable to this change.

2023-04-05 13:22 UTC, Kodiologist commented
@jakevdp Given that you deleted jakevdp/fix-lineno, how can I fetch the commit with the test?

2023-04-05 14:26 UTC, nicoddemus commented
I'm fine with that test too. :+1:

2023-04-05 15:33 UTC, jakevdp commented
Sorry, force of habit – I pushed the branch again.

2023-04-05 19:06 UTC, Kodiologist commented
Thanks. Added.

2023-04-05 19:53 UTC, nicoddemus commented
@RonnyPfannschmidt you OK with that test?

2023-04-05 21:48 UTC, RonnyPfannschmidt approved these changes
Yes, thanks for bringing it together

2023-04-06 01:48 UTC, merged

2023-04-06 01:48 UTC, nicoddemus commented
Thanks everyone!