Committing changes made in issue 10328
pytest-dev/pytest pull request #10935
Opened 2023-04-22 21:12 UTC by nondescryptid

Updated attempt to check encoding warnings as in https://github.com/pytest-dev/pytest/pull/10328/, as dependencies have been updated in the past 6 months.

2023-04-25 08:54 UTC, The-Compiler requested changes

2023-04-25 08:54 UTC, The-Compiler commented on testing/python/fixtures.py
> +                    return {}
This indentation change seems to be wrong and breaking tests currently.

2023-06-21 09:08 UTC, bluetech approved these changes
Nice work, I didn't think anyone would have the endurance to do this one :)

I suggest merging this quickly to avoid conflicts and regressions.

2023-06-21 09:08 UTC, bluetech commented on src/_pytest/helpconfig.py
> +        debugfile = open(path, "w", encoding="utf-8")
This fixes #7781 I think.

2023-06-21 12:13 UTC, The-Compiler requested changes
Amazing work, thanks @Zac-HD! I noticed a couple of small things, but I agree we should aim to merge this quickly (and I'm looking forward to turning this warning on for my own project finally!).

2023-06-21 12:13 UTC, The-Compiler commented on testing/test_parseopt.py
> +            encoding=sys.getdefaultencoding(),
Same as above (though I suppose it hardly matters with a `bash --version`)

2023-06-21 12:13 UTC, The-Compiler commented on tox.ini
> +    # Testing changes made in https://github.com/pytest-dev/pytest/pull/10328/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449
I don't really see what the point of this comment is - wouldn't it be better for people to find this via `git blame` if needed?

2023-06-21 16:33 UTC, Zac-HD commented on src/_pytest/pytester.py
> +            encoding=sys.getdefaultencoding(),
Oops, yes!

2023-06-21 17:58 UTC, The-Compiler approved these changes
Thanks again! IMHO this deserves its own changelog entry to make downstream projects aware that they can now use this, but that could be done in a follow up PR too.

2023-06-21 18:04 UTC, merged

2023-07-21 11:01 UTC, nondescryptid commented
Oh my goodness. @The-Compiler So sorry about not responding earlier to your request for changes. I didn't receive notifications for this and only realised this had been merged when I was looking through my account's commit history and wondered why I had a commit to pytest. Massive thanks to you, @bluetech and @Zac-HD!

2023-07-21 12:13 UTC, The-Compiler commented
All good, no worries! We got it all merged, and it still was a good starting point :)