Switch to new-style pluggy hook wrappers
pytest-dev/pytest pull request #11123
Opened 2023-06-19 11:59 UTC by bluetech

Fix #11122.

2023-06-19 15:21 UTC, nicoddemus approved these changes
Great work!

2023-06-19 17:23 UTC, nicoddemus requested changes
Let's wait on https://github.com/pytest-dev/pluggy/issues/405 before moving this forward. :+1:

2023-06-21 06:55 UTC, bluetech commented
Updated, pending pluggy 1.2.0 release (the pluggymain variants should pass).

2023-07-14 20:12 UTC, bluetech commented
Rebased, should be good to merge.

2023-07-14 21:17 UTC, nicoddemus commented on changelog/11122.improvement.rst
Wonder if this should be considered an improvement? Feels more like an internal change that does not affect users, so perhaps `trivial` would be more appropriate?

2023-07-14 21:18 UTC, nicoddemus approved these changes

2023-07-15 07:03 UTC, bluetech commented on changelog/11122.improvement.rst
It has some behavioral changes in exception handling, however mostly I want plugin authors to see it, so let's keep it as improvement.

2023-07-15 07:03 UTC, merged