Ensure the docstring is a string
pytest-dev/pytest pull request #11143
Opened 2023-06-26 06:44 UTC by tushar-deepsource

2023-06-26 08:33 UTC, RonnyPfannschmidt approved these changes
Thanks, I'm under the impression this regression came out of the new expressions handling and we can simplify this once python 3.7 support is dropped

2023-06-26 11:14 UTC, The-Compiler requested changes
Thanks for the fix! It'd be great if you could do those:

- [x] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/main/changelog/README.rst) for details.

  Write sentences in the **past or present tense**, examples:

  * *Improved verbose diff output with sequences.*
  * *Terminal summary statistics now use multiple colors.*

  Also make sure to end the sentence with a `.`.

- [x] Add yourself to `AUTHORS` in alphabetical order.

I also think we should backport this to 7.4 once merged.

2023-06-26 12:36 UTC, bluetech commented
Yep this was definitely an oversight in 9335a0b4453dbb08a07b6ac1b33d1ed3d17c45a5.

Along with this change we should also audit the other changes in that commit, but I can do it separately.

2023-07-04 17:18 UTC, Zac-HD approved these changes

2023-07-04 17:47 UTC, merged