Improve pytest.raises docs
pytest-dev/pytest pull request #11578
Opened 2023-11-02 21:20 UTC by nicoddemus

* Mention that subclassse are also matched.
* Improve some formatting and add some cross referencing.

Fix #11577

2023-11-03 14:33 UTC, Zac-HD approved these changes
Looks great!  Thanks Nicodemus 😃

2023-11-04 10:09 UTC, dhruvk12 approved these changes
Looks good

2023-11-04 10:24 UTC, merged

2023-11-04 10:25 UTC, The-Compiler requested changes

2023-11-04 10:25 UTC, The-Compiler commented on doc/en/how-to/assert.rst
> +        assert type(excinfo.value) is RuntimeError
```suggestion
        assert excinfo.type is RuntimeError
```

2023-11-04 10:25 UTC, The-Compiler commented on doc/en/how-to/assert.rst
> +    def test_recursion_depth():
Seems like this name is outdated/wrong?

2023-11-04 15:35 UTC, nicoddemus commented
@The-Compiler thanks for the catch, opened #11586 to follow up.

2023-11-04 18:34 UTC, The-Compiler commented
Thanks! Looks like @Zac-HD merged this in the exact same minute I reviewed it 😅