Clarified `markers` ini property. Fix #11738
pytest-dev/pytest pull request #11739
Opened 2023-12-26 10:57 UTC by MarcBresson

Clarified `markers` ini property. Fix #11738

- [x] Include documentation when adding new features.
- [ ] Include new tests or update existing tests when applicable.
- [X] Allow maintainers to push and squash when merging my commits. Please uncheck this if you prefer to squash the commits yourself.

If this change fixes an issue, please:

- [x] Add text like ``closes #XYZW`` to the PR description and/or commits (where ``XYZW`` is the issue number). See the [github docs](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information.

Unless your change is trivial or a small documentation fix (e.g., a typo or reword of a small section) please:

- [ ] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/main/changelog/README.rst) for details.

  Write sentences in the **past or present tense**, examples:

  * *Improved verbose diff output with sequences.*
  * *Terminal summary statistics now use multiple colors.*

  Also make sure to end the sentence with a `.`.

- [ ] Add yourself to `AUTHORS` in alphabetical order.
-->

2023-12-26 11:00 UTC, RonnyPfannschmidt approved these changes
thanks

2023-12-26 11:11 UTC, MarcBresson commented
I reopened the issue to ask one more question:

    Any reason why "`the mark expressions do not have a ini variant`"?

_Originally posted by @MarcBresson in https://github.com/pytest-dev/pytest/issues/11738#issuecomment-1869453551_

If you are interested, I could work on that (I don't think it should be too complicated since everything is already laid out)

2023-12-30 10:34 UTC, bluetech requested changes

2023-12-30 10:34 UTC, bluetech commented on doc/en/reference/reference.rst
> +      markers (linelist):   Register new markers for test functions
This part of the docs is actually generated from running `pytest --help`. The place you want to change is here:

https://github.com/pytest-dev/pytest/blob/52db918a27b2eb5043de6e80215076a98b0b9fff/src/_pytest/mark/__init__.py#L108

2024-01-03 11:04 UTC, nicoddemus approved these changes

2024-01-03 12:20 UTC, bluetech approved these changes

2024-01-03 12:20 UTC, merged