add track exception in pytest_fixture_post_finalizer hook
pytest-dev/pytest pull request #12164
Opened 2024-03-26 04:20 UTC by ShurikMen

solution #12163

2024-04-10 10:14 UTC, rplevka commented
I was just about to submit a PR with almost identical code changes when I discovered yours :)
Changes are looking great, but I think you want to append the new-hook reference to the docs [here](https://github.com/pytest-dev/pytest/blob/1f001cd1051a4ca4bef251d93e472e625578aaf7/doc/en/reference/reference.rst#L772)

2024-04-19 15:11 UTC, rplevka commented
that failing test does not seem to be related to the contributed code

2024-04-22 12:51 UTC, RonnyPfannschmidt approved these changes
this looks good to me, how does this interact with pytest-asyncio?

2024-04-23 02:48 UTC, ShurikMen commented
> this looks good to me, how does this interact with pytest-asyncio?

For pytest-asyncio, everything should work without additional improvements

2024-05-06 19:57 UTC, bluetech requested changes
Marking "Request changes" as per my comment on the issue: https://github.com/pytest-dev/pytest/issues/12163#issuecomment-2096797077

@ShurikMen  @rplevka please let me know in the issue if you have any specific use case for `pytest_fixture_teardown` instead of extending `pytest_fixture_post_finalizer`

2024-07-19 02:18 UTC, ShurikMen commented
> Marking "Request changes" as per my comment on the issue: [#12163 (comment)](https://github.com/pytest-dev/pytest/issues/12163#issuecomment-2096797077)
> 
> @ShurikMen @rplevka please let me know in the issue if you have any specific use case for `pytest_fixture_teardown` instead of extending `pytest_fixture_post_finalizer`

I use it like this https://github.com/pytest-dev/pytest/issues/12163#issuecomment-2097359368

2024-09-27 08:26 UTC, ogajduse commented
@bluetech Can the community be of any help to help to push this PR forward? The discussion in #12163 seems to be waiting for your response.

2024-09-30 08:48 UTC, rplevka commented
@RonnyPfannschmidt help, please? I think this has been stale for some time. We think the change makes perfect sense and we would really find it useful in our project.
Thank you.

2024-10-01 06:34 UTC, RonnyPfannschmidt commented
im also waiting for a reply from @bluetech - i think the concerns mentioned need to be addressed

2024-10-03 09:23 UTC, ogajduse commented
@RonnyPfannschmidt Are there any concerns that should be addressed by the community? If so, could you please let us know what are these? I believe that concerns @bluetech had were answered in #12163.
It is already 5 months since this has been open. I would like to know whether there is any chance merging it or we should be looking into a completely different approach or a place to put the logic in.

2024-10-31 12:26 UTC, RonnyPfannschmidt commented
@bluetech ping - can we add a fresh comment here whats still missing to progress this - its unclear to me if the reply in the issue addressed your concern sufficiently or not

2025-05-13 13:55 UTC, RonnyPfannschmidt commented
i did some re-reading - and the concerns haven't been resolved - i need a better understanding of the use-case and  actual exampel of the use-ases involved as im getting a X-Y problem gut feeling

2026-07-22 12:42 UTC, Zac-HD commented
Closing as obsolete: the underlying proposal in #12163 was closed as not_planned after the maintainers' concerns (preferring to extend `pytest_fixture_post_finalizer`, and the unclear use case) went unaddressed.

2026-07-22 12:42 UTC, closed without merging