Update runner.py
pytest-dev/pytest pull request #12191
Opened 2024-04-06 21:02 UTC by anitahammer

![Screenshot from 2024-04-06 21-48-46](https://github.com/pytest-dev/pytest/assets/166057949/8c8ae3b7-22bb-4297-a1e0-6d03c474bab4)

2024-04-07 12:31 UTC, nicoddemus requested changes
Thanks @anitahammer indeed this is a much better UX.

Could you please also:

1. Add a test for this to ensure we do not regress in the future. Probably a simple way to simulate this is to make a module raise `KeyboardInterrupt` during import and check that the session was interrupted and the message `!!! KeyboardInterrupt !!!!!!!!!` showed up.
2. Add a CHANGELOG entry
3. Add yourself to `AUTHORS` (optional)

2024-04-08 07:59 UTC, anitahammer commented
Thank you for the feedback @nicoddemus ! I've added a test case and verified that it was failing before my changes.

2024-05-02 11:38 UTC, nicoddemus commented on changelog/12191.bugfix.rst
> +Finally fixed the issue where keyboard interrupts and system exits were not being respected during the tests collection phase in pytest! No more frustration of tests not ending correctly — happy test
I like this message, but to keep in tone with the rest of our change log messages:

```suggestion
Keyboard interrupts and system exits are now probably handled during the test collection.
```

2024-05-02 11:40 UTC, nicoddemus commented
Thanks @anitahammer for the ping!

2024-05-02 11:45 UTC, nicoddemus approved these changes
Thanks a lot @anitahammer!

2024-05-02 11:59 UTC, merged