implement #12231 new flag --xfail-tb
pytest-dev/pytest pull request #12262
Opened 2024-04-28 02:13 UTC by okken

This implements issue #12231, making xfail tracebacks optional.   
Introduces a new flag --xfail-tb, that acts just like --tb, but just for xfail tracebacks.  

With this feature in place, turning off xfail tracebacks is as simple as `--xfail-tb=no`, and even works when `-rx` or `-ra` are present.
   
This is a first pass at the PR.  
- One test has been modified. 

Still todo:                                     
- Modify documentation for new flag
- Create changelog entry 
- I think that's it ??

2024-04-28 12:50 UTC, nicoddemus requested changes
Thanks @okken for tackling this so quickly!

As you mention indeed we still need tests and docs for this, but also I would like to see some other specific tests:

1. a normal failure and an xfail failure, with `tb=line` and `xfail-tb=auto`, and check the output.
2. I suppose just changing `--xfail-tb` default to `no` will require update some test(s), but if not, we need to check that the default does not produce any xfail tracebacks.

2024-04-28 12:50 UTC, nicoddemus commented on src/_pytest/terminal.py
> +        default="auto",
I think we should use `no` as default in this case, to get the pre-8.1.0 behavior, as people has been side tracked by this a lot (including myself at work, where we have some xfail in places).

```suggestion
        default="no",
```

We will need to mention this decision very clearly in the changelog.

2024-04-28 12:50 UTC, nicoddemus commented on src/_pytest/terminal.py
> +        style=None,
```suggestion
        style: Optional[str]=None,
```

2024-04-28 20:01 UTC, okken commented
I've written a rather verbose changelog entry. Feel free to shorten, tighten, completely rewrite, make suggestions, etc.

2024-04-28 20:33 UTC, okken commented
@nicoddemus I think I've done all necessary changes

2024-04-28 20:36 UTC, okken commented
I didn't quite do the tests as requested. by "a normal failure and an xfail failure, with tb=line and xfail-tb=auto, and check the output."
1. I didn't see the "a normal failure and" part until just now. I can add that.
2. None of the --tb tests use auto, but use short. So I did that.

Right now I've got a -rx test, an -rx --xfail-tb=short, and an -rx --xfail-tb=line test.

I think that's sufficient.
But if you'd like me to add the "and normal failure" part to the test, I can do that also.

2024-04-29 15:06 UTC, okken commented
Converting to draft, because I'm still working on it, and thinking about behavior. see #12231 for discussion and questions

2024-05-01 21:58 UTC, closed without merging

2024-05-02 03:36 UTC, okken commented
Accidentally deleted my fork, along with this branch. 
I've recreated the PR as #12280