implement #12231 new flag --xfail-tb
pytest-dev/pytest pull request #12280
Opened 2024-05-02 03:35 UTC by okken

This implements issue #12231, making xfail tracebacks optional. 
Add `--xfail-tb` flag, which turns traceback output for XFAIL results.

* If the `--xfail-tb` flag is not sent, tracebacks for XFAIL results are NOT shown.
* The style of traceback for XFAIL is set with `--tb`, and can be `auto|long|short|line|native|no`.
* Note: Even if you have `--xfail-tb` set, you won't see them if `--tb=no`.

Some history:

* This is a behavior break, but brings default behavior back to pre-8.0.0 behavior.
* With this change, default `-rx`/ `-ra` behavior is identical to pre-8.0 with respect to xfail tracebacks.
* With pytest 8.0, `-rx` or `-ra` would not only turn on summary reports for xfail, but also report the tracebacks for xfail results.
* This caused issues with some projects that utilize xfail, but don't want to see all of the xfail tracebacks.
* This change detaches xfail tracebacks from `-rx`, and now we turn on xfail tracebacks with `--xfail-tb`.

2024-05-04 14:35 UTC, nicoddemus requested changes
Looks great, thanks @okken!

I have left some minor requests, please take a look.

2024-05-04 14:35 UTC, nicoddemus commented on changelog/12231.feature.rst
> +Add `--xfail-tb` flag, which turns traceback output for XFAIL results.
```suggestion
Added `--xfail-tb` flag, which turns on traceback output for XFAIL results.
```

2024-05-04 14:35 UTC, nicoddemus commented on changelog/12231.feature.rst
> +* This change detaches xfail tracebacks from `-rx`, and now we turn on xfail tracebacks with `--xfail-tb`.
Nice!

IMHO this explains the history a bit better (mostly reordered the items):

```suggestion
With pytest 8.0, `-rx` or `-ra` would not only turn on summary reports for xfail, but also report the tracebacks for xfail results. This caused issues with some projects that utilize xfail, but don't want to see all of the xfail tracebacks.

This change detaches xfail tracebacks from `-rx`, and now we turn on xfail tracebacks with `--xfail-tb`. With this, the default `-rx`/ `-ra` behavior is identical to pre-8.0 with respect to xfail tracebacks. While this is a behavior change, it brings default behavior back to pre-8.0.0 behavior, which ultimately was considered the better course of action.
```

2024-05-04 14:35 UTC, nicoddemus commented on src/_pytest/terminal.py
> +        style: Optional[str] = None,
I think it makes sense to always require `style`, as it is only called from two places and those always pass `style`.

```suggestion
        sep_title: str,
        *,
        style: str,
        needed_opt: Optional[str] = None,        
```

2024-05-04 14:35 UTC, nicoddemus commented on testing/test_terminal.py
> +            "*test_xfail_tb_line.py:10: assert 3 == 4",
Let's also match `short test summary info` to ensure the summary happened before it.

```suggestion
            "*test_xfail_tb_line.py:10: assert 3 == 4",
            "*short test summary info*",
```

2024-05-04 14:35 UTC, nicoddemus commented on testing/test_terminal.py
> +            "*E       assert 3 == 4*",
```suggestion
            "*E       assert 3 == 4*",
            "*short test summary info*",
```

2024-05-04 22:43 UTC, okken commented
> Looks great, thanks @okken!
> 
> I have left some minor requests, please take a look.

Thanks @nicoddemus. I like all the suggestions.

2024-05-04 22:45 UTC, okken commented
Let me know if there's anything else needed.

2024-05-04 23:09 UTC, nicoddemus approved these changes
Thanks, looks great! 

I will let it open for a few more days to give others a chance of reviewing it too. 👍

2024-05-04 23:09 UTC, nicoddemus commented
(Note: we should squash/merge this)

2024-05-06 19:31 UTC, bluetech approved these changes
LGTM, thanks!

2024-05-07 13:09 UTC, okken commented
@nicoddemus Squash and merge ok now? Or wanna wait a bit more?

2024-05-07 17:37 UTC, merged

2024-05-07 17:37 UTC, nicoddemus commented
Thanks @okken!