cacheprovider: perform atomic writes
pytest-dev/pytest pull request #12410
Opened 2024-06-02 21:24 UTC by amezin

Make `Cache.set()` safe to use together with xdist.

2024-06-02 23:27 UTC, RonnyPfannschmidt requested changes
This is a false security as disagreement between workers will still cause confusion 

There's a reason why plugins like last failed put writes onto the co-ordinator

2025-01-06 06:36 UTC, Tusenka approved these changes

2025-01-06 06:47 UTC, RonnyPfannschmidt reviewed
This one is false security 

Cache writes should happen on the controller else workers with different state may still destroy each others data 

Its still a good idea to  have atomic writes for multi pytest invocations 

I intend to do  a more thorough review when im back in the office

2025-01-06 07:35 UTC, Tusenka approved these changes

2025-01-08 02:48 UTC, amezin commented
Honestly I already forgot why I needed this.

But I can resolve the conflicts if you want

2025-03-01 15:04 UTC, nicoddemus commented
Better wait for a more concrete case then, thanks @amezin anyway!

2025-03-01 15:04 UTC, closed without merging