📝 Make "setuptools entrypoint" term generic
pytest-dev/pytest pull request #12469
Opened 2024-06-17 15:53 UTC by webknjaz

This feature grew out of `setuptools` but the modern interface for extracting this information from the distribution package metadata is `importlib.metadata`. So the patch attempts to reflect this in the documentation messaging.

Refs:
* https://docs.python.org/3/library/importlib.metadata.html#entry-points
* https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata
* https://packaging.python.org/en/latest/specifications/entry-points/#entry-points

2024-06-17 16:07 UTC, The-Compiler approved these changes

2024-06-18 07:10 UTC, RonnyPfannschmidt commented on src/_pytest/config/__init__.py
> +            # We don't autoload from distribution package entry points,
3rd party package entry points

2024-06-18 07:10 UTC, RonnyPfannschmidt commented on src/_pytest/helpconfig.py
> +        lines.append("distribution package registered plugins:")
Perhaps `plugins discovered via entry-point`

2024-06-18 08:15 UTC, The-Compiler commented
I didn't want to start bikeshedding the terminology, but since we started already, here's my $0.02:

- Indeed "distribution package registered plugins" is a bit unwieldy
- However, "entry point registered plugins", while accurate, is most likely not a term newcomers that aren't familiar with Python packaging terminology will understand, so I don't exactly like it either... Fine to use in comments and such I suppose, but for user-facing output, I'd prefer something requiring less insider knowledge.

Some more ideas:

- Packaged plugins
- External(ly installed) plugins
- Third-party plugins
- Python package plugins
- Global plugins (as opposed to local plugins / conftest.py; or builtin core plugins)

IMHO I'd go for "third-party plugins". It's very clear and has little room for confusion. The only thing that could be confusing is that plugins even inside pytest-dev are considered "third-party", but if you interpret "third-party" as "not shipped with pytest (first-party) and not part of your project (second-party, kind of?)", I think it'd be both concise and accurate.

2024-06-18 08:23 UTC, The-Compiler requested changes
Also needs some doc changes:

```
doc/en/how-to/writing_plugins.rst
20:  `setuptools entry points`_
45:4. by loading all plugins registered through `setuptools entry points`_.
136:.. _`setuptools entry points`:
145:a feature that is provided by :std:doc:`setuptools <setuptools:index>`.
269:the ``setuptools``'s entry point technique.
```

```
doc/en/how-to/usage.rst
157:* The entry-point name of a plugin. This is the name passed to ``setuptools`` when the plugin is
```

```
doc/en/how-to/fixtures.rst
1934:Usually projects that provide pytest support will use :ref:`entry points <setuptools entry points>`,
```

```
doc/en/example/simple.rst
215:    # setuptools plugin
1077:(setuptools entry points) doesn't work with frozen executables so pytest
```

```
doc/en/reference/reference.rst
653:Bootstrapping hooks called for plugins registered early enough (internal and setuptools plugins).
1150:When set, disables plugin auto-loading through setuptools entrypoints. Only explicitly specified plugins will be
```

2024-06-18 13:15 UTC, RonnyPfannschmidt approved these changes

2024-06-18 13:19 UTC, The-Compiler requested changes
Looks like some links (e.g. to "entry points") are broken in writing_plugins now (missing `:ref:` for Sphinx?)

2024-06-19 11:53 UTC, webknjaz commented
@The-Compiler fixed!

@RonnyPfannschmidt Could you label the PR with the backport label? Does this need a change note since the terminology update is user-facing?

2024-06-20 08:05 UTC, The-Compiler approved these changes
Seems fine to me! Don't think this needs a changelog personally, but maybe a trivial change one, since we have that category anyways?

2024-06-20 08:26 UTC, The-Compiler submitted a review, later dismissed

2024-06-20 08:26 UTC, The-Compiler commented on changelog/12469.doc.rst
> +-- by :user:`webknjaz`
nitpick: we don't typically have that kind of thing for any other [changelog entry](https://docs.pytest.org/en/latest/changelog.html)

2024-06-20 09:31 UTC, merged

2024-06-20 13:56 UTC, jaraco reviewed
LGTM