Add more parameters to overridable methods for parameterized ID creation
pytest-dev/pytest pull request #12628
Opened 2024-07-18 10:13 UTC by NicoloBorghi

Suggesting new feature for parameterized ID name creation. In this way, all overridable options get the same set of arguments as the main _idval method.

2024-07-18 19:13 UTC, RonnyPfannschmidt reviewed
I like the idea

We need to ensure backwards compatibility and I'd like to bike shed about argument names a little

2024-07-18 19:13 UTC, RonnyPfannschmidt commented on src/_pytest/python.py
> +            id = self.idfn(val, argname, idx)
This is a breaking change,the old signature needs to be supported as well 

I recommend using a callable protocol as starting points

2024-07-19 14:27 UTC, nicoddemus requested changes
We also need to update the docs, for example: https://docs.pytest.org/en/stable/example/parametrize.html

Besides this, as @RonnyPfannschmidt commented, this feature needs to be backward compatible, but I'm not sure how we can do that easily.

2024-07-19 15:59 UTC, nicoddemus commented
> I apologize for putting up such rough code (mostly due to lack of experience). If you don't mind, we could find a way. Otherwise, feel free to decline and close this PR.

2024-12-06 08:32 UTC, Tusenka approved these changes

2026-05-03 06:11 UTC, bluetech commented
@NicoloBorghi thanks for the PR, but it seems a bit stuck so I'll close it as stale. If you (or anyone else reading) wants this feature, I suggest opening an issue where we can discuss how to add it with backward compat in mind.

2026-05-03 06:11 UTC, closed without merging