Fix `pytest.mark.usefixtures()` without arguments silently erroring
pytest-dev/pytest pull request #13008
Opened 2024-11-28 20:17 UTC by daara-s

Closes #12426

2024-11-29 12:33 UTC, nicoddemus requested changes

2024-11-29 12:33 UTC, nicoddemus commented on testing/python/fixtures.py
> +        reprec.assertoutcome(failed=1)
This is good, but I feel we should test the actual message, using `pytest.runpytest()` and `fnmatch_lines()`.

2024-11-29 19:09 UTC, nicoddemus approved these changes
Thanks @daara-s for picking this up, and also thanks to @JiajunXu2 for the initial PR. 👍

2024-11-30 00:12 UTC, The-Compiler commented
Oh, that's unfortunate... Like you say I suppose pytest-bdd could do the decorating manually and conditionally, in the same way as just [below the linked code snippet](https://github.com/pytest-dev/pytest-bdd/blob/93e446eff667b9f4f450ea239d19a19e335590c7/src/pytest_bdd/scenario.py#L284-L290):

```python
        example_parametrizations = collect_example_parametrizations(templated_scenario)
        if example_parametrizations is not None:
            # Parametrize the scenario outlines
            scenario_wrapper = pytest.mark.parametrize(
                "_pytest_bdd_example",
                example_parametrizations,
            )(scenario_wrapper)
```

cc @youtux @jsa34 as a heads-up.

2024-11-30 10:06 UTC, daara-s commented
@The-Compiler [this what you mean](https://github.com/pytest-dev/pytest-bdd/pull/746)?

2024-11-30 13:30 UTC, daara-s commented
Got ahead of myself with the revert. Still need to bump the plugin pin.

@youtux what's the release cadence for pytest-bdd?

2024-11-30 13:32 UTC, youtux commented
We don't really have a schedule, just whenever we think it's needed.

2024-12-01 11:08 UTC, merged

2024-12-01 11:09 UTC, nicoddemus commented
Thanks @daara-s and @JiajunXu2 for the work here! 👍

2024-12-01 15:15 UTC, JiajunXu2 commented
Sorry for stepping away from the pr, I've been a bit busy lately. Thank you @daara-s for finishing it, and everyone for the support!