Apply PEP 639
pytest-dev/pytest pull request #13014
Opened 2024-11-30 11:52 UTC by nicoddemus

Prompted by this post https://bsky.app/profile/hynek.me/post/3lc5n7g6kr22f

Ref: https://github.com/python-attrs/attrs/pull/1377

2024-11-30 12:09 UTC, nicoddemus commented
Thanks @hynek for sharing. 👍

2024-11-30 12:09 UTC, nicoddemus commented
Hmmm seems like setuptools does not support this new format yet?

`attrs` uses `hatch` and the same configuration worked there.

2024-11-30 12:38 UTC, The-Compiler commented
Looks like it's WIP:

- [[FR] Implement PEP 639 · Issue #4629 · pypa/setuptools](https://github.com/pypa/setuptools/issues/4629)
- [Add initial support for license expression (PEP 639) by cdce8p · Pull Request #4706 · pypa/setuptools](https://github.com/pypa/setuptools/pull/4706)

2024-11-30 12:46 UTC, nicoddemus commented
Thanks @The-Compiler for looking into it.

Keeping this on-hold until a new version is released then.

2024-11-30 13:21 UTC, RonnyPfannschmidt commented
Part of me would like to go hatch

2025-03-01 16:26 UTC, nicoddemus commented
PR: https://github.com/pypa/setuptools/pull/4829

2025-06-18 08:34 UTC, bluetech approved these changes
Should be good now. Will kick a rebase to make sure.

2025-06-18 09:46 UTC, RonnyPfannschmidt requested changes
We need to set a higher minimum setuptools version

2025-06-18 10:38 UTC, bluetech commented
> We need to set a higher minimum setuptools version

Right, went ahead and did it, hopefully @nicoddemus doesn't mind :)

2025-06-19 18:46 UTC, webknjaz approved these changes

2025-07-24 14:00 UTC, nicoddemus commented
> Right, went ahead and did it, hopefully @nicoddemus doesn't mind :)

Not at all of course, thanks!

Failure is due to:

https://github.com/tox-dev/tox/issues/3565

2025-07-26 01:33 UTC, merged