Bugfix for approx on mismatched dictionaries
pytest-dev/pytest pull request #13046
Opened 2024-12-09 10:06 UTC by dvdliu

### Main Changes
Closes https://github.com/pytest-dev/pytest/issues/12444

### Tests
Regression test added for the issue mentioned in the above issue

2024-12-19 14:26 UTC, marcelotrevisani commented
It is missing the changelog, could you please add it?

2024-12-20 16:42 UTC, marcelotrevisani commented
@nicoddemus , I also had this problem recently and this seems to be a nice fix. Could you review and approve if you are fine with it please?

2024-12-26 07:48 UTC, RonnyPfannschmidt requested changes
I believe its necessary to report tge additional keys

2024-12-26 07:48 UTC, RonnyPfannschmidt commented on src/_pytest/python_api.py
> +        for approx_key, approx_value in approx_side_as_map.items():
I just noted that the fix ignores additional keys in the other side

2025-03-01 15:01 UTC, nicoddemus commented
Closing as this has not seen activity in awhile.

Feel free to reopen if you want to work on this again.

2025-03-01 15:01 UTC, closed without merging