Issues a warning when a function is not collected as a test case just because it uses `@pytest.fixture` (#12989)
pytest-dev/pytest pull request #13051
Opened 2024-12-11 10:41 UTC by dongfangtianyu

close #12989 .

- [x] Include documentation when adding new features.
- [x] Include new tests or update existing tests when applicable.
- [X] Allow maintainers to push and squash when merging my commits.
- [x] Create a new changelog file in the `changelog` folder

A function is declared as a test case using the convention of the `test` prefix in its name ， or as a fixture using the `pytest.fixture` decorator.

When both are used simultaneously, it is not possible to have both a test case and a fixture.

So a warning is issued to remind the user: no test case, only a fixture.

Example

```python
import pytest

@pytest.fixture
def test_function():
    pass

```

```
(venv) C:\Users\administrator\pytest\demo>pytest
============================= test session starts ==============================
platform win32 -- Python 3.12.0, pytest-8.4.0.dev262+gf160963c4.d20241211, pluggy-1.5.0
rootdir: C:\Users\administrator\pytest\demo
configfile: pytest.ini
plugins: hypothesis-6.111.0, xdist-3.6.1
collected 0 items                                                               

=============================== warnings summary =============================== 
test_aa.py:1
  C:\Users\administrator\pytest\demo\test_aa.py:1: PytestCollectionWarning: ca
nnot collect test function 'test_function',because it used the '@pytest.fixture' than becomes a fixture (from: test_aa.py)
    import warnings

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================== 1 warning in 0.26s ==============================
```

2024-12-11 11:48 UTC, dongfangtianyu commented
Probably should add an ini config that allows old projects to ignore this warning?

2025-02-20 19:30 UTC, jakkdl requested changes
I'm probably in favor of introducing a warning, I'm not sure what fixture requires being named `test_`; and if so they *can* suppress the warning. But it might be a better fit for https://pypi.org/project/flake8-pytest-style/

2025-03-01 14:45 UTC, nicoddemus requested changes

2025-03-01 14:45 UTC, nicoddemus commented on doc/en/explanation/fixtures.rst
> +Distinguishing fixtures and tests
I agree.

2025-03-01 14:45 UTC, nicoddemus commented on changelog/12989.improvement.rst
> +This helps beginners distinguish fixtures from tests; experienced users can ignore the warning via config.
```suggestion
A warning is now issued when a fixture uses the same name convention as a test function, for example a fixture named `test_user`.

This helps preventing beginners that expect anything named `test_` to be considered a test.
```

However I'm not convinced this warning is really necessary... besides being noisy for a common pattern (`test_user` is a good example of a fixture which provides a "test user", a "user for testing"), even if somebody confuses it is not the end of the world, because being a fixture, it will usually be called *anyway* by another test function (and if not then the user did not understand anything related to fixtures and functions and the warning won't help much anyway). It would make more sense if the situation was that the code were not being called at all (so silently being ignored), but this is not the case here.

I'm -0 on this:

* Noisy for a common and valid pattern.
* Even if a beginner confuses the two, the downside is not so severe because the fixture will be called anyway.

2025-03-03 11:06 UTC, jakkdl commented on changelog/12989.improvement.rst
> +This helps beginners distinguish fixtures from tests; experienced users can ignore the warning via config.
silently-being-ignored sounds very tricky to catch, especially once you factor in partial runs with `-k` etc. That's for `codecov` to catch, although beginners probably wouldn't have that configured.

A lint rule does sound more suitable for this

2025-03-03 11:08 UTC, jakkdl commented
I've been convinced that pytest isn't the right place to catch this, so with three people voting against (if weakly) I'm closing this

2025-03-03 11:08 UTC, closed without merging