Add Sphinx-compatible docstrings and inline comments for main.py (lines 245-490)
pytest-dev/pytest pull request #13091
Opened 2024-12-29 22:28 UTC by mohammadaminjohari

This pull request addresses issue #12979 by enhancing the documentation and readability of the file pytest/src/_pytest/main.py in the range of lines 245 to 490.
Changes Made:

    Docstrings Added:
        All functions and classes in the specified range now include Sphinx-compatible docstrings with:
            A brief overview of the purpose of each function or class.
            Detailed descriptions of parameters (names, types, and expected values).
            Return values and their types.
            Possible exceptions raised by the functions.

    
        Added meaningful inline comments to clarify complex logic and improve code readability.

Functions and Classes Updated:

    validate_basetemp: Validates the base temporary directory path.
    wrap_session: Executes the pytest session in a controlled wrapper.
    pytest_cmdline_main: The main entry point for pytest command-line execution.
    _main: The default protocol for session initialization, test running, and reporting.
    pytest_collection: Handles the collection phase of pytest sessions.
    pytest_runtestloop: Manages the test run loop for pytest sessions.

    All changes were verified locally by running the test suite using tox. No errors or warnings were encountered.

    Please review the changes and let me know if further modifications are needed.
    

Best regards,
Mohammadamin Johari

2024-12-31 06:04 UTC, dongfangtianyu requested changes
Thanks @mohammadaminjohari for PR, just 2 suggestions for reference:
1. Keep the style of the docstring consistent with the existing pytest code, for example, 
   - content:  https://docs.pytest.org/en/stable/_modules/_pytest/hookspec.html#pytest_addoption, 
   -  html: https://docs.pytest.org/en/stable/reference/reference.html#pytest.hookspec.pytest_addoption

3. Do not modify the inline comments for now, it is not necessary at first glance

2024-12-31 06:16 UTC, Pierre-Sassoulas reviewed
Thanks you for opening the PR. I started a review but @dongfangtianyu did something more detailled, i'll just leave what I had. About inline comment in particular : Commentting what the code does is duplicating informations, inline comment should be about why the code is done this way not what it does.

2025-01-02 05:19 UTC, dongfangtianyu commented
Hi @mohammadaminjohari , 
I received a reminder of the review request, but did not see any new changes. If available, you can continue to commit and push on the this branch.

2025-03-01 14:58 UTC, nicoddemus commented
Closing for now, feel free to reopen when you get a chance to work on this again.

2025-03-01 14:58 UTC, closed without merging