Update writing_plugins.rst
pytest-dev/pytest pull request #7896
Opened 2020-10-14 19:00 UTC by nimeshvashistha

fixes #7212

2020-10-15 00:59 UTC, nicoddemus requested changes

2020-10-15 00:59 UTC, nicoddemus commented on doc/en/writing_plugins.rst
> +    Some functions should be implemented only in plugins or conftest.py files situated at the
```suggestion
    Some hooks should be implemented only in plugins or conftest.py files situated at the
```

2020-10-15 00:59 UTC, nicoddemus commented on doc/en/writing_plugins.rst
> +    tests root directory due to how pytest discovers plugins during startup.
```suggestion
    tests root directory due to how pytest discovers plugins during startup,
    see the documentation of each hook for details.
```

2020-10-15 00:59 UTC, nicoddemus commented
Thanks @nimeshvashistha! Two small tweaks and LGTM! 👍

2020-10-15 09:38 UTC, The-Compiler commented
#7212 specifically mentions the `pytest_collection_modifyitems` hook - so I guess something should be added to that hook (rather than just a general notice) as well?

2020-10-15 14:10 UTC, nimeshvashistha commented
> #7212 specifically mentions the `pytest_collection_modifyitems` hook - so I guess something should be added to that hook (rather than just a general notice) as well?

Sure, I'm willing to contribute more, can you please guide me a bit about it?

2020-10-15 14:47 UTC, nicoddemus commented
> Sure, I'm willing to contribute more, can you please guide me a bit about it?

I think a note under the [pytest_collection_modifyitems](https://docs.pytest.org/en/stable/reference.html#pytest.hookspec.pytest_collection_modifyitems) hook mentioning that, if implemented in `conftest.py` files, it always receives all collected items, not only those under the `conftest.py`.

2020-10-16 06:44 UTC, nimeshvashistha commented
> > Sure, I'm willing to contribute more, can you please guide me a bit about it?
> 
> I think a note under the [pytest_collection_modifyitems](https://docs.pytest.org/en/stable/reference.html#pytest.hookspec.pytest_collection_modifyitems) hook mentioning that, if implemented in `conftest.py` files, it always receives all collected items, not only those under the `conftest.py`.

alright, I've made the changes.

2020-10-16 12:41 UTC, nicoddemus commented on doc/en/reference.rst
> +    If this hook is implemented in conftest.py files, it always receives all collected items, not only those
```suggestion
    If this hook is implemented in ``conftest.py`` files, it always receives all collected items, not only those
```

2020-10-16 12:41 UTC, nicoddemus commented on doc/en/reference.rst
> +    under the conftest.py.
```suggestion
    under the ``conftest.py`` where it is implemented.
```

2020-10-16 12:42 UTC, nicoddemus approved these changes
Thanks @nimeshvashistha!

(We should squash merge this PR)

2020-10-17 11:26 UTC, merged