Add pythonenv* to gitignore
pytest-dev/pytest pull request #8002
Opened 2020-11-06 14:37 UTC by mcsitter

GitHub Codespaces automatically create a pythonenv folder. For example: `pythonenv3.8/` which containts a virtual environment. This should not be commited by default.

2020-11-06 21:52 UTC, bluetech reviewed
I don't see any harm in adding it. Just to reduce potential of this unintentionally ignoring something in the future, can reduce the scope a bit:

1. If this is a directory, add `/` at the end.
2. If it always at the top directory, add a `/` at the start.

2020-11-11 12:21 UTC, nicoddemus requested changes
(Just to explicitly change the PR status as "changes requested", as per @bluetech's requests).

2020-11-13 20:02 UTC, mcsitter commented
Applied the requested changes. Thanks for approving this! This is a major quality of life improvement for me.

2020-11-13 21:14 UTC, bluetech approved these changes

2020-11-13 21:14 UTC, merged