Migrate from testdir to pytester
pytest-dev/pytest pull request #8019
Opened 2020-11-09 17:23 UTC by JosiasAurel

2020-11-10 06:22 UTC, duthades requested changes

2020-11-10 06:22 UTC, duthades commented on testing/test_faulthandler.py
> +        pytester.tmpdir,
```suggestion
        pytester.path,
```

2020-11-10 06:22 UTC, duthades commented on testing/test_faulthandler.py
> +def test_already_initialized(faulthandler_timeout, pytester: Pytester):
```suggestion
def test_already_initialized(faulthandler_timeout: int, pytester: Pytester) -> None:
```

2020-11-10 06:37 UTC, duthades commented
Hi @JosiasAurel, thanks for contributing.

I have left some comments. It seems there are some test and linting errors. Nothing major. I suggest that you create an environment locally so that you run tests and linting checks and easily fix errors if any. You can find 'How to' details [here](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#preparing-pull-requests) (It has both short and long version descriptions).

2020-11-11 17:24 UTC, duthades requested changes

2020-11-11 17:24 UTC, duthades commented on testing/test_faulthandler.py
> +from _pytest.pytester import Pytester
Add a line after this import.
```suggestion
from _pytest.pytester import Pytester

```

2020-11-13 08:35 UTC, bluetech approved these changes
Thanks @JosiasAurel, this looks good! And thanks @duthades for the review.

2020-11-13 08:36 UTC, merged