Call Python 3.8 doCleanup and doClassCleanup.
pytest-dev/pytest pull request #8033
Opened 2020-11-13 10:29 UTC by PetterS

Fixes #8032 

Also adds support for doCleanups, because the features are identical.

2020-11-14 20:01 UTC, bluetech requested changes
Thanks @PetterS, LGTM with a few comments. The extensive tests are nice.

I see there is also a new `addModuleCleanup` but that'd be more tricky to support since the code for `setUpModule`/`tearDownModule` is not in the unittest plugin for some reason.

2020-11-16 07:52 UTC, PetterS commented on src/_pytest/unittest.py
> +            "<no cleanup function>",
I agree. Done.

2020-11-16 07:52 UTC, PetterS commented on src/_pytest/unittest.py
> +    def docleanup(self):
Done.

Linter would not let me assign a lambda to a variable so it looks like this now.

2020-11-16 07:52 UTC, PetterS commented on src/_pytest/unittest.py
> +            except Exception:
Done.

2020-11-16 07:52 UTC, PetterS commented on testing/test_unittest.py
> +    sys.version_info < (3, 1), reason="Feature introduced in Python 3.1"
Done

2020-11-16 07:52 UTC, PetterS commented on testing/test_unittest.py
> +            def test_one(self):
Done.

2020-11-16 07:53 UTC, PetterS commented on testing/test_unittest.py
> +        class Second(unittest.TestCase):
Done!

2020-11-16 07:53 UTC, PetterS commented on testing/test_unittest.py
> +        class Second(unittest.TestCase):
Done!

2020-11-16 07:55 UTC, PetterS commented
I think this patch still can be improved. The `pass_self` branches for cleanup are not taken. I added those for consistency.

2020-11-16 16:08 UTC, bluetech approved these changes
Thanks, I think it's good to go. Will merge in a couple of days in case someone else also wants to review.

2020-11-16 16:16 UTC, PetterS commented
Cheers! This will help our internal development!

2020-11-19 10:07 UTC, merged

2020-12-07 12:31 UTC, PetterS commented
@bluetech Do you know when the next release of pytest will be?

2020-12-07 12:43 UTC, bluetech commented
@PetterS Planned for this Saturday (see #8101)

2020-12-07 13:22 UTC, PetterS commented
Cheers, thanks!