Add small section on migrating from nose to pytest.
pytest-dev/pytest pull request #8048
Opened 2020-11-18 19:30 UTC by mickeypash

This change was initiated after a discussion found [here](https://github.com/pytest-dev/pytest/discussions/8024#discussioncomment-127351).

The section currently features the `nose2pytest` tool with plans to expand
on some of the common gotchas when performing such migrations.

Questions for reviewers:
- Should I update the the CHANGELOG - I think it's not necessary.
- Should I add myself to AUTHORS - the change seems pretty small so I'll leave it for now.

2020-11-18 22:42 UTC, nicoddemus commented
> Should I update the the CHANGELOG - I think it's not necessary.

I don't think it is necessary; I believe only sweeping changes to the documentation are useful to be added to the CHANGELOG. 👍 

> Should I add myself to AUTHORS - the change seems pretty small so I'll leave it for now.

Yes by all means. 😁

2020-11-18 22:44 UTC, nicoddemus requested changes
A few minor adjustments. 👍 

Thanks!

2020-11-18 22:44 UTC, nicoddemus commented on doc/en/nose.rst
> +Migrating from Nose to Pytest
```suggestion
Migrating from nose to pytest
```

pytest is always spelled  with lower-case P, and I believe it's the same case with nose if the docs are any indication:

https://nose.readthedocs.io/en/latest/testing.html

2020-11-18 22:44 UTC, nicoddemus commented on doc/en/nose.rst
> +and py.test plugin to help convert Nose-based tests into py.test-based tests.
```suggestion
and pytest plugin to help convert Nose-based tests into pytest-based tests.
```

We've dropped the dot a few years back. 😁

2020-11-18 22:56 UTC, mickeypash commented
I've included your suggestions and added my name to AUTHORS by force pushing to my `patch-1` branch. The change hasn't been reflected here.

2020-11-18 23:24 UTC, nicoddemus commented
(Let me know if you want me to rebase/force-push for you)

2020-11-18 23:57 UTC, mickeypash commented
Yes please

2020-11-19 10:07 UTC, mickeypash commented
Is there a way I can re-trigger the failed steps?

2020-11-19 11:51 UTC, nicoddemus commented
> Is there a way I can re-trigger the failed steps?

Unfortunately not, only maintainers can re-trigger (except for pushing a new commit of course).

2020-11-19 12:02 UTC, merged

2020-11-19 12:02 UTC, nicoddemus commented
Thanks @mickeypash!