run pyupgrade-docs
pytest-dev/pytest pull request #8366
Opened 2021-02-23 15:49 UTC by verhovsky

a follow up to #5705

since pytest supports only Python 3.6+, we can use f-strings in the documentation

2021-02-24 12:46 UTC, nicoddemus commented
LGTM, thanks a lot for that and writing https://github.com/verhovsky/pyupgrade-docs. 👍 

Could you also add that to our pre-commit configuration? Thanks!

2021-02-24 14:40 UTC, verhovsky commented
@nicoddemus done.

thanks for writing/maintaining pytest, it's one of my favorite libraries!

2021-02-24 18:46 UTC, nicoddemus approved these changes
LGTM, thanks!

(Note to squash this before we merge it)

2021-02-25 15:25 UTC, asottile requested changes
just making sure you saw this @verhovsky (since you're not watching the repo): https://github.com/verhovsky/pyupgrade-docs/issues/3

2021-02-25 16:14 UTC, verhovsky commented
@asottile I pinned pyupgrade's minor version to `2.10.*` and released it as pyupgrade-docs v0.2.4. I hope that works for you.

2021-03-20 11:15 UTC, nicoddemus approved these changes
Thanks @verhovsky!

@asottile anything else needs to be done here?

2021-03-20 15:06 UTC, asottile commented
> 
> 
> Thanks @verhovsky!
> 
> @asottile anything else needs to be done here?

yeah we probably shouldn't use the tool since it integrates in an incompatible and unsupported way (and likely will either break or be stuck on an old version)

2021-03-20 15:51 UTC, nicoddemus commented
@asottile thanks!

@verhovsky thanks anyway for the PR! Perhaps once the issues (which I'm not familiar with TBH) are fixed, you can open another PR? Thanks!

2021-03-20 15:51 UTC, closed without merging

2021-03-20 16:13 UTC, RonnyPfannschmidt commented
@asottile any opinion on allowing pyupgrade to be invoked as a python function? i'm under the impression they just don't want to take a "i has no api" and i see  providing a explicit minimal api as opportunity to make tooling easier

2021-03-20 16:14 UTC, asottile commented
no I don't want to provide an api because it paints me into a corner and prevents me from adding features.  the only supported api is the entrypoint

2021-03-20 16:23 UTC, RonnyPfannschmidt commented
@asottile i was thinking along the lines of exposing a "limited" api in the sense of having only a `parse_args` and a `fix_content(args, original_content)` with a explicit note that the type/strucutre of the parsed args is open

2021-03-20 16:24 UTC, asottile commented
no thanks, they might as well use the entrypoint at that point

2021-03-20 16:37 UTC, RonnyPfannschmidt commented
@asottile i see, in that case it may be necessary to document that, also stdio replacement is still a pain