issue a warning when Item and Collector are used in diamond inheritance
pytest-dev/pytest pull request #8447
Opened 2021-03-14 22:03 UTC by RonnyPfannschmidt

2021-03-16 08:51 UTC, bluetech reviewed
I think it's a good idea to warn about it, so +1 from me.

I left some suggestions on the wording.

2021-03-16 08:51 UTC, bluetech commented on testing/test_nodes.py
> +def test_subclassing_node_with_item_warns() -> None:
```suggestion
def test_subclassing_both_item_and_collector_warns() -> None:
```

2021-03-16 08:51 UTC, bluetech commented on changelog/8447.deprecation.rst
> +Instead of inheritance composition should be used.
```suggestion
Defining a custom pytest node type which is both an item and a collector now issues a warning.
It was never sanely supported and triggers hard to debug errors.

Instead, a separate collector node should be used, which collects the item. See :ref:`nonpython` for an example.
```

2021-03-16 08:51 UTC, bluetech commented on src/_pytest/nodes.py
> +    def __init_subclass__(cls):
```suggestion
    def __init_subclass__(cls) -> None:
```

2021-06-05 22:34 UTC, RonnyPfannschmidt commented
will complete the docs tommorow morning

2021-06-07 09:48 UTC, The-Compiler commented
CI failures (other than the `docs` failure) are unrelated, see https://github.com/codecov/codecov-action/issues/330.

FWIW we've had a plugin at work which had the same issue as in #8435, but without any diamond inheritance involved. It looks like this has been resolved somewhere along the way though, as I now don't see any issues with either the `main` branch nor this PR and the plugin.

Other than that, I'll let someone else review, as I'm not too familiar with this part of the code.

2021-06-07 10:02 UTC, The-Compiler requested changes
Just a couple of things from a quick look.

2021-06-07 10:06 UTC, RonnyPfannschmidt commented on src/_pytest/nodes.py
> +            sig.replace()
good catch,

i initially removed self and used binding (but noted that the binding was just not working out as i liked)

its no longer used

2021-06-07 10:08 UTC, RonnyPfannschmidt commented on src/_pytest/nodes.py
> +            sig = signature(cast(Type[Node], self).__init__)
yeah, that might be a good call in that particular location

2021-06-07 10:09 UTC, RonnyPfannschmidt commented on src/_pytest/nodes.py
> +            known_kw = {k: v for k, v in kw.items() if k in sig.parameters}
modern constructors are expected to pass over unknown arguments
legacy/broken ones did not

but an extra warning should be added

2021-06-07 20:53 UTC, RonnyPfannschmidt commented on src/_pytest/nodes.py
> +            known_kw = {k: v for k, v in kw.items() if k in sig.parameters}
done

2021-06-07 20:53 UTC, RonnyPfannschmidt commented on src/_pytest/nodes.py
> +            sig = signature(cast(Type[Node], self).__init__)
getattr actually works and is even better

2021-06-07 20:53 UTC, RonnyPfannschmidt commented on src/_pytest/nodes.py
> +            sig.replace()
fixed

2021-06-09 20:04 UTC, nicoddemus approved these changes
Overall looks good, seems you missed a TODO in the code. 👍

2021-06-09 20:04 UTC, nicoddemus commented on src/_pytest/nodes.py
> +                "TODO: doc link",
TODO left here.

2021-06-10 08:04 UTC, RonnyPfannschmidt commented on src/_pytest/nodes.py
> +                "TODO: doc link",
done thanks

2021-06-10 11:24 UTC, nicoddemus commented
@RonnyPfannschmidt just a ping in case you missed it, but a test needs update it seems. 👍

2021-06-10 11:30 UTC, RonnyPfannschmidt commented
Will fix as soon as I can access a computer

2021-06-12 16:28 UTC, bluetech commented
I understand the `__init_subclass__` change (which LGTM), but I don't understand the other changes, to e.g. `FSCollector` and the constructors, and how they are related to the diamond inheritance issue, can you explain?

2021-06-13 05:47 UTC, RonnyPfannschmidt commented
They restore the ability to use the pattern, i accidentally broke it before (which caused issues to projects)

2021-06-17 08:58 UTC, The-Compiler requested changes
I'll have to agree that I don't really follow about the `FSCollector` changes unfortunately. We should probably at least have a test demonstrating what worked with 6.2, breaks with `main`, but works again with this PR?

2021-06-17 09:09 UTC, RonnyPfannschmidt commented
The test added does that

In particular the constructor used, 

i will attach a log once I return

2021-06-17 15:28 UTC, RonnyPfannschmidt commented
@The-Compiler 


pytest on main with the test having the warnings removed will do the following

test: ```python


def test_subclassing_both_item_and_collector_deprecated(request, tmp_path: Path) -> None:
    """
    verifies we warn on diamond inheritance
    as well as correctly managing legacy inheritance ctors with missing args
    as found in plugins
    """

    class SoWrong(nodes.File, nodes.Item):
        def __init__(self, fspath, parent):
            """Legacy ctor with legacy call # don't wana see"""
            super().__init__(fspath, parent)

    SoWrong.from_parent(
        request.session, fspath=legacy_path(tmp_path / "broken.txt")
    )
```

out: ```
$ pytest testing/test_nodes.py -k test_subclassing_both_item_and_collector_deprecated --tb=native
================================================================================================================================= test session starts ==================================================================================================================================
platform linux -- Python 3.9.5, pytest-6.3.0.dev515+g46269d90d.d20210617, py-1.10.0, pluggy-0.13.1
rootdir: /home/ronny/Projects/pytest-dev/pytest, configfile: pyproject.toml
collected 17 items / 16 deselected / 1 selected                                                                                                                                                                                                                                        

testing/test_nodes.py F                                                                                                                                                                                                                                                          [100%]

======================================================================================================================================= FAILURES =======================================================================================================================================
_________________________________________________________________________________________________________________ test_subclassing_both_item_and_collector_deprecated __________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/ronny/Projects/pytest-dev/pytest/testing/test_nodes.py", line 56, in test_subclassing_both_item_and_collector_deprecated
    SoWrong.from_parent(
  File "/home/ronny/Projects/pytest-dev/pytest/src/_pytest/nodes.py", line 587, in from_parent
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)
  File "/home/ronny/Projects/pytest-dev/pytest/src/_pytest/nodes.py", line 237, in from_parent
    return cls._create(parent=parent, **kw)
  File "/home/ronny/Projects/pytest-dev/pytest/src/_pytest/nodes.py", line 128, in _create
    return super().__call__(*k, **kw)
TypeError: __init__() got an unexpected keyword argument 'path'
=============================================================================================================================== short test summary info ================================================================================================================================
FAILED testing/test_nodes.py::test_subclassing_both_item_and_collector_deprecated - TypeError: __init__() got an unexpected keyword argument 'path'
=========================================================================================================================== 1 failed, 16 deselected in 0.01s ===========================================================================================================================
```
with the extra support code it passes

2021-06-17 15:31 UTC, RonnyPfannschmidt commented
@The-Compiler done

2021-06-24 09:45 UTC, The-Compiler approved these changes
I still really can't claim to fully understand the topic, but I played around a bit with [partially reverting](https://paste.the-compiler.org/view/82f296a9) changes and indeed [stuff breaks](https://paste.the-compiler.org/view/8c80ae56) when doing that.

Given that @nicoddemus was fine with it earlier and there aren't any other comments, let's finally get this in! :tada: Thanks @RonnyPfannschmidt for the persistence!

2021-06-24 09:45 UTC, merged

2021-06-24 09:51 UTC, RonnyPfannschmidt commented
@The-Compiler this one is a real backward compatibility pain, i hope we can take the mechanisms behind it out of the picture soon

i'm not happy we have to have this workaround for now