address #8361 - introduce hook caller wrappers that enable backward compat
pytest-dev/pytest pull request #8463
Opened 2021-03-18 22:18 UTC by RonnyPfannschmidt

2021-03-18 22:22 UTC, asottile commented
change makes sense, probably need a test or two to demonstrate the behaviour (do we want a warning and to eventually migrate?)

2021-03-19 00:51 UTC, nicoddemus commented
I also think this is a good approach to #8361. 👍

2021-03-20 20:55 UTC, bluetech requested changes
Thanks for looking at this.

As I mentioned, I don't think we really *need* to do this, but if we can have a way to deprecate, I guess it's OK.

I *think* wrapping at the `config.hook` level is not sufficient -- some of the hooks use an `FSHookProxy`  (`gethookproxy`) which uses the plugin manager directly. I think if possible it would be better to add this directly on the `PytestPluginManager`.

I'm also think this might have some non-negligible effect on performance but I didn't measure. Can do once it's further along.

2021-03-20 21:57 UTC, RonnyPfannschmidt commented on src/_pytest/main.py
> +            proxy = PathAwareHookProxy(FSHookProxy(pm, remove_mods))
@bluetech here i wrap that one

2021-03-20 22:16 UTC, RonnyPfannschmidt commented
@bluetech i believe, in a followup i can even add some bits to ensure the cost can be removed if people opt out of legacy paths

2021-03-29 12:02 UTC, nicoddemus requested changes
Overall great work, please see my comments!

2021-04-02 11:52 UTC, nicoddemus commented on doc/en/deprecations.rst
> +In order to support the transition oto pathlib, the following hooks added additional arugments:
```suggestion
In order to support the transition to :mod:`pathlib`, the following hooks now receive additional arguments:
```

2021-04-02 11:56 UTC, nicoddemus commented on doc/en/deprecations.rst
> +*  ``pytest_ignore_collect(fspath: pathlib.Path)``
```suggestion
*  :func:`pytest_ignore_collect(fspath: pathlib.Path) <_pytest.hookspec.pytest_ignore_collect>`
```

2021-04-02 11:57 UTC, nicoddemus commented on doc/en/deprecations.rst
> +*  ``pytest_collect_file(fspath: pathlib.Path)``
*  :func:`pytest_collect_file(fspath: pathlib.Path) <_pytest.hookspec.pytest_collect_file>`

2021-04-02 11:57 UTC, nicoddemus commented on doc/en/deprecations.rst
> +*  ``pytest_pycollect_makemodule(fspath: pathlib.Path)``
```suggestion
*  :func:`pytest_collect_file(fspath: pathlib.Path) <_pytest.hookspec.pytest_collect_file>`
```

2021-04-02 11:57 UTC, nicoddemus commented on doc/en/deprecations.rst
> +*  ``pytest_report_header(startpath: pathlib.Path)``
```suggestion
*  :func:`pytest_collect_file(fspath: pathlib.Path) <_pytest.hookspec.pytest_collect_file>`
```

2021-04-02 11:57 UTC, nicoddemus commented on doc/en/deprecations.rst
> +*  ``pytest_report_collectionfinish(startpath: pathlib.Path)``
```suggestion
*  :func:`pytest_collect_file(fspath: pathlib.Path) <_pytest.hookspec.pytest_collect_file>`
```

2021-04-02 12:00 UTC, nicoddemus commented on doc/en/deprecations.rst
> +The accompanying ``py.path.local`` based paths have been deprecated.
```suggestion
The accompanying ``py.path.local`` based paths have been deprecated: plugins which manually invoke those hooks should only pass the new ``pathlib.Path`` arguments, and users should change their hook implementations to use the new ``pathlib.Path`` arguments.
```

2021-04-03 10:46 UTC, RonnyPfannschmidt commented on src/_pytest/config/compat.py
> +                            pylib_path_arg=fspath_var, pathlib_path_arg=path_var
fixed

2021-04-04 20:23 UTC, asottile approved these changes
looks good!  thanks for the good tests

![](https://i.fluffy.cc/b6wlBbdVkX83CHpLWxHZw74WJxHVQc9S.gif)

2021-04-05 20:06 UTC, nicoddemus approved these changes

2021-04-05 20:42 UTC, bluetech approved these changes
LGTM!

2021-04-05 20:50 UTC, merged