Support approximate comparisons between Decimal and float
pytest-dev/pytest pull request #8513
Opened 2021-04-02 20:40 UTC by kalekundert

Fixes #8495

2021-04-02 21:44 UTC, asottile requested changes

2021-04-02 21:44 UTC, asottile commented on src/_pytest/python_api.py
> +            result: bool = low <= actual <= high
if we encounter a `TypeError` here we should not give users a false confidence that this works (when it only works sometimes)

I've demonstrated a specific case here: https://github.com/pytest-dev/pytest/issues/8495#issuecomment-812688829

2021-04-03 06:39 UTC, RonnyPfannschmidt requested changes

2021-04-03 06:39 UTC, RonnyPfannschmidt commented on src/_pytest/python_api.py
> +            low = self.expected - self.tolerance
this must always trigger a warning as, as both precision and behavior are slightly differet

2021-04-03 06:39 UTC, RonnyPfannschmidt commented on testing/python/approx.py
> +            (Decimal("1.0000005"), Decimal("1.0"), Decimal),
this looks like a candidate for longer names and parametrize

2024-06-20 11:58 UTC, obestwalter commented
@kalekundert are you still interested in following this up? Otherwise it is better to close this and maybe have another go from a clean slate at a later point.

2024-12-15 11:15 UTC, Tusenka approved these changes

2025-03-01 15:07 UTC, closed without merging