pygments themes are customizable
pytest-dev/pytest pull request #8752
Opened 2021-06-11 15:21 UTC by azmeuk

This patchs allows users to set two environment variables (*PYTEST_THEME* and *PYTEST_THEME_MODE*) to customize the pygments theme to use. It fixes #7132

I know some people were interested in [rich](https://github.com/willmcgugan/rich) and suggested to wait and see, but this solution is so easy and unintrusive I think it might be worth right now.

What do you think?

2021-06-11 15:46 UTC, azmeuk commented
I can. What do you expect? Catching the pygments exception and raise a custom exception with a nicer error message when the environment variables have invalid values?

2021-06-11 16:03 UTC, nicoddemus requested changes
Thanks a lot @azmeuk!
 
Please also add the new variables to the `reference.rst` file, in the "Environment Variables" section.

2021-06-11 16:03 UTC, nicoddemus commented on doc/en/reference/customize.rst
> +- **PYTEST_THEME_MODE** sets this style to *light* or *dark*
```suggestion
- **PYTEST_THEME_MODE** sets this style to *light* or *dark*.
```

2021-06-11 16:03 UTC, nicoddemus commented on changelog/7132.feature.rst
> +Added two environment variables ``PYTEST_THEME`` and ``PYTEST_THEME_MODE`` to let the users customize the pygments theme used.
I think it would be nice to add a link to the docs here (possibly just change the env vars to `:envvar:PYTEST_THEME`, I think).

2021-06-11 17:00 UTC, azmeuk commented
I added some tests and applied your suggestions.

2021-06-11 17:01 UTC, azmeuk commented on src/_pytest/_io/terminalwriter.py
> +        from _pytest.config.exceptions import UsageError
I let this import inside the function to avoid a circular import error.

2021-06-11 17:26 UTC, nicoddemus approved these changes
Thanks @azmeuk! Looks great!

Left two other suggestions, otherwise LGTM. 👍

2021-06-11 17:26 UTC, nicoddemus commented on src/_pytest/_io/terminalwriter.py
> +                    "PYTEST_THEME environment variable had an invalid value. "
One more suggestion: could we include the value of `PYTEST_THEME` into the message? This often helps when debugging errors/tracebacks from environments other than yours.

2021-06-11 17:26 UTC, nicoddemus commented on src/_pytest/_io/terminalwriter.py
> +                    "PYTEST_THEME_MODE environment variable had an invalid value. "
Same suggestion here to include the value of the environment variable into the message. 👍

2021-06-11 17:29 UTC, azmeuk commented
Done :)

2021-06-11 17:57 UTC, The-Compiler requested changes
I don't want to bikeshed this, but I wonder why it should be an environment variable, when (almost) all other things are either ini settings or commandline arguments?

We already have `--code-highlight` from #6934, so why not `--code-highlight-theme` and `--code-highlight-theme-mode` or so?

2021-06-11 18:21 UTC, nicoddemus commented
I'm 👍 on configuring this as env vars... my thinking is that this is something you might want change just for yourself because of preference/color blindness issues, and this is not easily done with config vars (you can of course use command-line vars indirectly with `PYTEST_ADDOPTS`).

2021-06-11 19:18 UTC, azmeuk commented
I suggested an environment variable because of [this comment](https://github.com/pytest-dev/pytest/issues/6984#issuecomment-778825560), and because each contributor of a given project may have its own terminal configuration, and need its own color customization.

I am open to add/replace a command line argument though.

2021-06-11 19:25 UTC, RonnyPfannschmidt commented
unless pytest gets someething nice to unify config by env var, config file and cli argument im of the oppinion that this particular one is best placed in a env var, accompanied with some google search firendly docs for people that need it

2021-06-14 08:37 UTC, azmeuk commented
It looks like the failing tests are unrelated with this patch.

2021-06-14 09:16 UTC, RonnyPfannschmidt approved these changes

2021-06-14 12:36 UTC, nicoddemus commented
@The-Compiler do you agree with the reasoning for the environment variables? If so could you merge it then? Thanks! 🙇

2021-06-14 13:02 UTC, The-Compiler commented
Does this really work? I don't see a change in output when I set `PYTEST_THEME`, and the [TerminalFormatter](https://pygments.org/docs/formatters/#TerminalFormatter) we use doesn't seem to have a `style` option at all.

2021-06-14 13:21 UTC, nicoddemus commented
@azmeuk did you test this yourself? Can you post some screenshots please?

2021-06-14 15:07 UTC, azmeuk commented
> Does this really work? I don't see a change in output when I set `PYTEST_THEME`, and the [TerminalFormatter](https://pygments.org/docs/formatters/#TerminalFormatter) we use doesn't seem to have a `style` option at all.

I think you are right, I did not tested with other pygments themes. This [piece of documentation](https://github.com/pygments/pygments/blob/faf69c028f0efa7798a938163e8432d838acfda2/pygments/formatter.py#L31) indeed tells that `TerminalFormatter` does not use the `style` parameter. I will checks this out.

2021-06-14 15:58 UTC, RonnyPfannschmidt commented
https://github.com/pygments/pygments/blob/faf69c028f0efa7798a938163e8432d838acfda2/pygments/formatters/terminal256.py#L100 will use the color style, 

https://github.com/pygments/pygments/blob/faf69c028f0efa7798a938163e8432d838acfda2/pygments/formatters/terminal.py#L25-L58 will use a color scheme argument

i believe its very safe to usually pick the 256 formatter, lets figure how to correctly pick

2021-06-14 16:00 UTC, RonnyPfannschmidt commented
pygments itself does a explicit choice - https://github.com/pygments/pygments/blob/faf69c028f0efa7798a938163e8432d838acfda2/pygments/cmdline.py#L390-L395

i wonder if the color sceme can be worked into the details

2021-06-14 16:02 UTC, azmeuk commented
> i wonder if the color sceme can be worked into the details

What do you mean? Use the same trick as pygments to guess if a TerminalFormatter or a Terminal256Formatter should be used?

2021-06-14 16:03 UTC, RonnyPfannschmidt commented
@azmeuk no, i meant trying to figure of color schemes could be sensibly mapped to the low color terminal (or alternatively at least having color scemes for the visually imparied

2021-06-14 16:05 UTC, azmeuk commented
Now rereading my PR I guess it does not really have sense anymore unless we indeed use `Terminal256Formatter` instead of `TerminalFormatter`. Is it ok for you if I do the move?

2021-06-14 16:07 UTC, RonnyPfannschmidt commented
i'm going to be happy with formatter change

i believe for full compat we should do the same check pygments does (and print a warning if a color style is passed but not supported due to lack of 256 color terminals)

a followup then could be to provide a color sceme for the color-bind either by pygments directly or by addding one and upstreaming later

2021-06-14 17:16 UTC, The-Compiler commented
We're not really in "easy and unintrusive" terrain at that point anymore, IMHO... Even pygmentize gets this wrong, checking if 256 is in `$TERM` is by no means sufficient to check if the terminal supports 256 colors.

Case in point, here's the pygments default output with my terminal and `TerminalFormatter`:

![image](https://user-images.githubusercontent.com/625793/121932166-d500c600-cd44-11eb-9fb1-c1053b2acfa4.png)

and here when it switches to 256 color mode:

![image](https://user-images.githubusercontent.com/625793/121932204-e053f180-cd44-11eb-9487-6eff53851a2e.png)

So this would really make things less readable (and uniform) for many setups, rather than more so.

FWIW I still think the right solution to this is the user configuring the colors in their terminal (and sticking with the current 16-color formatter), rather than adding 256-color support just so that we can use pygment themes. Right now, the output looks like other colorized output (say, `ls` and such) in a terminal, while with hand-picked/hardcoded color themes, there's a much bigger chance for conflicts with how the rest of the terminal output looks.

2021-06-14 17:51 UTC, azmeuk commented
I have a custom set of terminal colors (solarized), every terminal utility displays well except pytest.
I think we could meet in the middle:
- If `PYTEST_THEME` is defined, use `Terminal256Color` or `TerminalTrueColorFormatter with the passed theme,
- Else use `TerminalFormatter`,
What do you think @The-Compiler?

2021-06-14 18:01 UTC, The-Compiler commented
I guess that'd work indeed!

2021-06-14 21:49 UTC, azmeuk commented
Ok here it is.
Here are some tests with the solarized, emacs, and tango themes.

![solarized-dark](https://user-images.githubusercontent.com/60163/121963882-012f3d80-cd6b-11eb-8b8f-e1a8ec68b725.png)
![emacs](https://user-images.githubusercontent.com/60163/121963876-ff657a00-cd6a-11eb-9c2b-47770ec801c2.png)
![tango](https://user-images.githubusercontent.com/60163/121963880-0096a700-cd6b-11eb-86da-b01ea2bc205e.png)

2021-06-15 09:04 UTC, RonnyPfannschmidt commented on testing/test_terminal.py
> +            color_mapping.format_for_fnmatch(
i think we can either drop call  to the color mapping formatter or add a mode where we can enter actual expected numbers for a color scheme (to read better than the raw escape sequences)

2021-06-15 13:19 UTC, hugovk reviewed
Just a little typo.

2021-06-15 13:19 UTC, hugovk commented on doc/en/reference/customize.rst
> +Its value can be any valid `pygment style <https://pygments.org/docs/styles/>`_.
```suggestion
Its value can be any valid `Pygments style <https://pygments.org/docs/styles/>`_.
```

2021-06-15 13:19 UTC, hugovk commented on doc/en/reference/reference.rst
> +Sets a `pygment style <https://pygments.org/docs/styles/>`_ to use for the code output.
```suggestion
Sets a `Pygments style <https://pygments.org/docs/styles/>`_ to use for the code output.
```

2021-06-15 13:19 UTC, hugovk commented on testing/test_terminal.py
> +            "Only valid pygment styles are allowed."
```suggestion
            "Only valid Pygments styles are allowed."
```

2021-06-15 13:19 UTC, hugovk commented on src/_pytest/_io/terminalwriter.py
> +                    "Only valid pygment styles are allowed.".format(
```suggestion
                    "Only valid Pygments styles are allowed.".format(
```

2021-06-15 21:43 UTC, azmeuk commented
@RonnyPfannschmidt @hugovk Thank you for your feedbacks, they are fixed.

2021-06-17 07:18 UTC, azmeuk commented
@The-Compiler Is this PR acceptable to you now?

2021-06-17 09:24 UTC, The-Compiler requested changes
Thanks for the update! Seems fine now, other than the [linting issues](https://results.pre-commit.ci/run/github/37489525/1623793629.DSRkRswNTduNuLir8BnprA). I added a couple of comments for the mypy ones.

2021-06-17 09:24 UTC, The-Compiler commented on testing/conftest.py
> +class _ColorMapping:
You could declare `COLORS: Dict[str, str]` here, so that mypy knows that it exists.

2021-06-17 09:24 UTC, The-Compiler commented on testing/conftest.py
> +        return [line.format(**cls.RE_COLORS) for line in lines]
Might want to create `RE_COLORS` here (or in an `__init__`, but I think it's fine to do it every time the function is called). That way, you don't need to duplicate `RE_COLORS = {k: re.escape(v) for k, v in COLORS.items()}` for all subclasses, and mypy will be happy as well.

2021-06-17 09:30 UTC, azmeuk commented
Here it is!

2021-06-20 17:55 UTC, azmeuk commented
@The-Compiler Ping! Would you consider accepting this PR now?

2021-06-20 19:04 UTC, The-Compiler commented
While test failures are unrelated, the [CI is still failing](https://results.pre-commit.ci/run/github/37489525/1623922295.nGxIv4bPRuqGJp538MioEg).

2021-06-20 19:22 UTC, azmeuk commented
Ok. This should be fixed now.

2021-06-20 20:33 UTC, The-Compiler approved these changes
Thanks! Looks good now, but I'm still confused about the test failures. I thought they were only something unrelated being flaky, but I can see them consistently happen in your branch, but apparently [not on the main branch](https://github.com/pytest-dev/pytest/commits/main). However, I'm unable to reproduce locally... anyone has an idea what's going on there?

2021-06-20 21:44 UTC, azmeuk commented
I rebased against the main branch, just in case.

2021-06-21 10:28 UTC, azmeuk commented
Different tests are failing each time, but the common thing is `ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>`. Not sure where it comes from.

2021-06-22 12:08 UTC, The-Compiler commented
I've been trying to reproduce with Python 3.9 in a Ubuntu 20.04 Docker container, but still no luck, unfortunately... Maybe someone else has an idea what could be going on.

2021-07-01 21:02 UTC, azmeuk commented
@nicoddemus @RonnyPfannschmidt do you maybe have any clue?

2021-07-25 16:40 UTC, azmeuk commented
I just tried -but failed- to reproduce the errors with [act](https://github.com/nektos/act).

2021-07-26 14:06 UTC, nicoddemus commented
> @nicoddemus @RonnyPfannschmidt do you maybe have any clue?

Sorry no clue :( 

Have you tried rebasing on the latest `main`?

2021-08-13 14:27 UTC, azmeuk commented
> Have you tried rebasing on the latest main?

Yep.

I found that the errors are raised randomly on different other tests due to `test_code_highlight_invalid_theme`. I suppose trying to access a non existing theme in pygments has side effects that make some other tests fails, depending on the order the are executed.

Here I am looking for unclosed file descriptors and warnings...

2021-08-13 16:58 UTC, nicoddemus commented
> I found that the errors are raised randomly on different other tests due to test_code_highlight_invalid_theme. I suppose trying to access a non existing theme in pygments has side effects that make some other tests fail, depending on the order the are executed.

If this is happening in a few tests, we can use `pytester.runpytest_subprocess()`, which will ensure no state will leak.

2021-08-13 18:26 UTC, azmeuk commented
> If this is happening in a few tests, we can use `pytester.runpytest_subprocess()`, which will ensure no state will leak.

:heart: :heart: :heart:
 
Tests are green now, this patch should be mergeable!

2021-08-13 18:59 UTC, nicoddemus commented
Woot! Thanks for the patience and following through with the PR! ❤️

2021-08-15 10:20 UTC, azmeuk commented
@nicoddemus @RonnyPfannschmidt @The-Compiler anyone interested in pressing the merge button?

2021-08-15 12:06 UTC, merged

2021-08-15 12:06 UTC, nicoddemus commented
Thanks!