Docs: monkeypatch.setenv does not accept bool
pytest-dev/pytest pull request #8874
Opened 2021-07-08 17:25 UTC by adamjstewart

The [`monkeypatch` docs](https://docs.pytest.org/en/6.2.x/reference.html?highlight=monkeypatch#pytest.monkeypatch.monkeypatch) show an example of passing `prepend=False` to `monkeypatch.setenv`. However, the [`monkeypatch.setenv` docs](https://docs.pytest.org/en/6.2.x/reference.html?highlight=monkeypatch#pytest.MonkeyPatch.setenv) clearly state that `prepend` is of type `str` or `None`. This PR fixes the `monkeypatch` docs.

2021-07-08 17:30 UTC, The-Compiler requested changes
Good catch! It looks like the same example is in `doc/en/builtin.rst` and `doc/en/how-to/monkeypatch.rst` too - could you adjust them as well?

I also wonder if we should use `prepend=None` instead, given that those examples mostly seem to show the default signature.

2021-07-08 17:43 UTC, adamjstewart commented
Done and done 😄

2021-07-09 13:24 UTC, nicoddemus approved these changes

2021-07-09 15:38 UTC, The-Compiler approved these changes

2021-07-09 15:38 UTC, merged