Add debug file
pytest-dev/pytest pull request #8955
Opened 2021-07-29 19:09 UTC by symonk

Hi all, hope you are well,

This patch adds capabilities to provide a customised file name to `--debug` which routes the debug logs into a file of the users choice.  I have proposed this because we use multiple pytest executions as part of one jenkins job and find we have a wealth of internal plugins, running each run with `--debug` and artifacting the log is useful for us on a per run basis, we run parallel tests with xdist (want the debug log) then isolated sequential tests in a single process (want the debug log) and by default, this overwrites the pytestdebug.log.  see #8954 for some of my reasoning.

This remains the same functionality to most users in the sense that:

There are now 3 options to `--debug`:

 - `--debug` in isolation will result in a `pytestdebug.log` file in the root directory as prior
 - `--debug` omitted from the command line (ini args etc) will result in no log file written
 - `--debug mylog` will result in `mylog.log` holding the debug logs

Notes:
 - `.log` is suffixed to the user file if it does not end in `.log` just to keep things relatively similar to the original file here
 - unit / integration tests added
 - caveat: This is now user input and we open with `w`, so there is a chance someone passes a file that exists and we truncate and write logs to it 🤔  

Let me know what you think,  thanks!

2021-07-29 19:16 UTC, symonk commented
windows `b` comes before `f` but not quite the same on unix* i guess, I'm a windows user at home so never spotted this

2021-07-30 12:01 UTC, nicoddemus reviewed
Looks good, thanks! Left a few comments, please take a look.

2021-07-30 12:01 UTC, nicoddemus commented on src/_pytest/helpconfig.py
> +def _resolve_debug_log_name(file_name: str) -> str:
As I mentioned, I don't think we need this.

2021-07-30 12:02 UTC, nicoddemus commented on testing/test_config.py
> +def test_debug_file_name_is_suffixed_with_dot_log() -> None:
Personally I would group those new tests into a class:

```python
class TestDebugOption:

    def test_suffixed_with_dot_log() -> None:
        ...
```

But that's just a matter of choice I guess.

2021-07-30 12:03 UTC, nicoddemus requested changes
Good work, thanks @symonk!

2021-07-30 18:28 UTC, symonk commented
> Good work, thanks @symonk!

Thanks again @nicoddemus for the review, should be sorted now, appreciate it.

2021-07-30 20:36 UTC, nicoddemus approved these changes
Thanks!

2021-07-30 20:37 UTC, merged