#8592: Officially deprecate pytest_cmdline_preparse
pytest-dev/pytest pull request #8956
Opened 2021-07-29 20:04 UTC by symonk

Hi all, I think this is how we handle these hook deprecations.

- officially deprecates the `pytest_cmdline_preparse` hook

Can I follow up by removing the `pytest_warning_captured` hook altogether? not sure when it was officially deprecated.

2021-07-30 12:05 UTC, nicoddemus requested changes
Great work!

Besides the comments above, please also add a new section to `doc/en/deprecations.rst`, with the deprecation and how to update the code. After that, add a link to that section to the changelog entry. 👍

2021-07-30 12:05 UTC, nicoddemus commented on changelog/8592.deprecation.rst
> +``pytest_cmdline_preparse`` has been officially deprecated.  It will be removed in a future release.  Use ``pytest_load_initial_conftests`` instead.
Looks good, thanks! See if you can add links to the two hooks.

2021-07-30 12:05 UTC, nicoddemus commented on testing/test_assertrewrite.py
> +def test_deprecation_of_cmdline_preparse(pytester: Pytester) -> None:
Please move this test to `testing/deprecated_test.py`.

2021-07-30 18:15 UTC, symonk commented
> Great work!
> 
> Besides the comments above, please also add a new section to `doc/en/deprecations.rst`, with the deprecation and how to update the code. After that, add a link to that section to the changelog entry. 👍

Thanks for your time to review @nicoddemus, should be fixed now - appreciate it

2021-07-31 13:52 UTC, nicoddemus approved these changes
Thanks @symonk, great work!

2021-07-31 13:53 UTC, merged

2021-07-31 13:56 UTC, nicoddemus commented
@symonk quick tip: when writing commit messages or PR descriptions, add a line like `close #123` to the commit body or PR description, so it will be automatically linked with that issue, and the issue will be closed when the PR gets merged.

More details: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2021-07-31 13:59 UTC, symonk commented
Thanks, I normally do that and for some reason I haven't been doing it recently (my bad!), will make sure to do it for new pull requests, thanks for merging 👍