Implement unpacking nested pytest.param objects in parametrize
pytest-dev/pytest pull request #9254
Opened 2021-10-31 08:53 UTC by vgorkavenko

This PR result of the discussion in https://github.com/pytest-dev/pytest/issues/9074

Now nested `pytest.param` objects will be unpacked to parent: nested values are placed in parent `pytest.param`, marks are merged, id is merged if parent `pytest.param` does not have id

2021-10-31 09:23 UTC, RonnyPfannschmidt reviewed
I like the initial idea as it enhances composition and user experience

Strictly speaking it may be necessary to start this as a opt out,

But enabling a opt out may be enough

Depending on luck i may be able to give this a deeper look later today

2021-11-07 09:37 UTC, vgorkavenko commented
@RonnyPfannschmidt, can we invite someone else to review?

2021-11-08 11:56 UTC, nicoddemus requested changes
I left a few comments/suggestions, however I'm -0.5 on the whole idea: I understand the problem that it tries to solve, but having this done automatically by the core feels a bit too magical to me.

2021-11-08 11:56 UTC, nicoddemus commented on changelog/9074.improvement.rst
> +Now ``pytest`` do unpack nested ``pytest.param`` values and merge their ids and marks.
```suggestion
Now ``pytest`` unpacks nested ``pytest.param`` values and merges their ids and marks.
```

2021-11-08 11:56 UTC, nicoddemus commented on changelog/9074.improvement.rst
> +If parent ``pytest.param`` has an id - it rewrites nested ids.
I think we can leave this phrase out, seems a bit too detailed for the changelog (this should live in its own docs).

```suggestion

```

2021-11-08 11:56 UTC, nicoddemus commented on changelog/9074.improvement.rst
> +Earlier in this case the values ``a, b, c`` in test are a ``ParameterSet`` objects
```suggestion
In previous versions, ``a, b, c`` were passed as ``ParameterSet`` objects.
```

2021-11-08 11:56 UTC, nicoddemus commented on src/_pytest/python.py
> +                normalized_values = []
I would prefer if we move this to a free function and add specific unittests for it.

2021-11-08 20:19 UTC, vgorkavenko commented
@nicoddemus Maybe we can add some argument to `parametrize` or `pytest.param` (`squash=True`, for example)? To make it less magical

2021-11-09 17:30 UTC, nicoddemus commented
Interesting, but if we want to make it less magical/more explicit, how about adding a function which merges the parameters? For example:

```python
@pytest.mark.parametrize(
    "a,b,c", [
        pytest.merge_params(
            pytest.param(1, id="one", marks=pytest.mark.one),
            pytest.param(2, id="two", marks=pytest.mark.two),
            pytest.param(3, id="three", marks=pytest.mark.three),
            marks=pytest.mark.full
        )
    ]
)
```

This explicit and doesn't require us to change the internals.

2021-11-12 06:28 UTC, RonnyPfannschmidt commented
I would propose a opt on/out bool kwonly parameter to pytest.param

Alternatively some kind of builder pattern

2021-11-12 09:49 UTC, nicoddemus commented
> Alternatively some kind of builder pattern

But still in pytest itself? My impression is that this is a bit exotic use case (but I don't have any data to back that up), better made available through a plugin.

2024-06-20 13:36 UTC, obestwalter commented
@vgorkavenko would you like to pick this up again and finish it up? Otherwise it seems more sensible to close for now and maybe pick the topic up later.

2024-06-20 13:37 UTC, closed without merging