Use safe_getattr() in getfixturemarker()
pytest-dev/pytest pull request #9880
Opened 2022-04-22 21:42 UTC by jparise

This could alternatively use `inspect.getattr_static` because `_pytestfixturefunction`
is an "internal" attribute that's only assigned by `FixtureFunctionMarker`, and it's
unlikely we'd need to support descriptors and dynamic attribute lookups.

2022-04-23 04:16 UTC, RonnyPfannschmidt requested changes
I roughly recall this was done intentionally to prevent hiding certain errors

2022-04-25 15:47 UTC, jparise commented
> I roughly recall this was done intentionally to prevent hiding certain errors

Yes, but I believe `safe_getattr` is equivalent to the previous logic:

```py
try:
    getattr(obj, "_pytestfixturefunction", None)
except TEST_OUTCOME:
    return None
return fixturemarker
```

And the implementation of `safe_getattr`:

```py
try:
    return getattr(object, name, default)
except TEST_OUTCOME:
    return default
```

I landed on this function while debugging a `pytest --collect-only` hang due to an "evil" `__getattr__` implementation in our code base.

2022-04-25 16:40 UTC, RonnyPfannschmidt approved these changes
Based on the reply this is good to go

2022-05-30 01:28 UTC, jparise commented
@RonnyPfannschmidt is this in good shape to merge, or are there any other revisions you'd propose?

2022-05-30 03:54 UTC, RonnyPfannschmidt commented
Pressing that button

2022-05-30 03:54 UTC, merged